using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HashGuard.Models;
using Newtonsoft.Json;

namespace HashGuard.Services
{
    /// <summary>
    /// Generates verification reports in multiple formats (TXT, JSON, CSV).
    /// </summary>
    public class ReportGenerator
    {
        /// <summary>
        /// Exports hash results to a plain text report.
        /// </summary>
        /// <param name="results">The hash results to export.</param>
        /// <param name="outputPath">The output file path.</param>
        public async Task ExportToTXT(List<FileHashResult> results, string outputPath)
        {
            ValidateParameters(results, outputPath);

            var sb = new StringBuilder();
            sb.AppendLine("╔══════════════════════════════════════════════════════════════╗");
            sb.AppendLine("║                  HashGuard Verification Report               ║");
            sb.AppendLine("╚══════════════════════════════════════════════════════════════╝");
            sb.AppendLine();
            sb.AppendLine($"Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"Files Processed: {results.Count}");
            sb.AppendLine($"Successful: {results.Count(r => r.Success)}");
            sb.AppendLine($"Failed: {results.Count(r => !r.Success)}");
            sb.AppendLine(new string('─', 62));

            foreach (var result in results)
            {
                sb.AppendLine();
                sb.AppendLine($"File: {result.FileName}");
                sb.AppendLine($"Path: {result.FilePath}");
                sb.AppendLine($"Size: {result.FileSizeFormatted}");
                sb.AppendLine($"Date: {result.ComputedAt:yyyy-MM-dd HH:mm:ss UTC}");

                if (result.Success)
                {
                    foreach (var hash in result.Hashes)
                    {
                        sb.AppendLine($"{hash.Key,-8}: {hash.Value}");
                    }
                }
                else
                {
                    sb.AppendLine($"ERROR: {result.ErrorMessage}");
                }

                sb.AppendLine(new string('─', 62));
            }

            sb.AppendLine();
            sb.AppendLine("Report generated by HashGuard - https://github.com/ZadgeIsCool/HashGuard");

            await File.WriteAllTextAsync(outputPath, sb.ToString());
        }

        /// <summary>
        /// Exports hash results to a JSON report.
        /// </summary>
        /// <param name="results">The hash results to export.</param>
        /// <param name="outputPath">The output file path.</param>
        public async Task ExportToJSON(List<FileHashResult> results, string outputPath)
        {
            ValidateParameters(results, outputPath);

            var report = new
            {
                Generator = "HashGuard",
                Version = "1.0.0",
                GeneratedAt = DateTime.UtcNow,
                TotalFiles = results.Count,
                SuccessCount = results.Count(r => r.Success),
                FailureCount = results.Count(r => !r.Success),
                Results = results.Select(r => new
                {
                    r.FileName,
                    r.FilePath,
                    r.FileSizeBytes,
                    FileSize = r.FileSizeFormatted,
                    r.ComputedAt,
                    r.Success,
                    r.ErrorMessage,
                    Hashes = r.Hashes.ToDictionary(
                        h => h.Key.ToString(),
                        h => h.Value)
                })
            };

            string json = JsonConvert.SerializeObject(report, Formatting.Indented);
            await File.WriteAllTextAsync(outputPath, json);
        }

        /// <summary>
        /// Exports hash results to a CSV report.
        /// </summary>
        /// <param name="results">The hash results to export.</param>
        /// <param name="outputPath">The output file path.</param>
        public async Task ExportToCSV(List<FileHashResult> results, string outputPath)
        {
            ValidateParameters(results, outputPath);

            var sb = new StringBuilder();
            sb.AppendLine("FileName,FilePath,FileSize,MD5,SHA1,SHA256,SHA512,ComputedAt,Success,Error");

            foreach (var result in results)
            {
                var fields = new[]
                {
                    EscapeCsvField(result.FileName),
                    EscapeCsvField(result.FilePath),
                    result.FileSizeFormatted,
                    result.Hashes.GetValueOrDefault(HashType.MD5, ""),
                    result.Hashes.GetValueOrDefault(HashType.SHA1, ""),
                    result.Hashes.GetValueOrDefault(HashType.SHA256, ""),
                    result.Hashes.GetValueOrDefault(HashType.SHA512, ""),
                    result.ComputedAt.ToString("yyyy-MM-dd HH:mm:ss"),
                    result.Success.ToString(),
                    EscapeCsvField(result.ErrorMessage ?? "")
                };

                sb.AppendLine(string.Join(",", fields));
            }

            await File.WriteAllTextAsync(outputPath, sb.ToString());
        }

        /// <summary>
        /// Escapes a field for CSV output, quoting if necessary.
        /// </summary>
        private static string EscapeCsvField(string field)
        {
            if (field.Contains(',') || field.Contains('"') || field.Contains('\n'))
            {
                return $"\"{field.Replace("\"", "\"\"")}\"";
            }
            return field;
        }

        /// <summary>
        /// Validates common parameters for export methods.
        /// </summary>
        private static void ValidateParameters(List<FileHashResult> results, string outputPath)
        {
            if (results == null || results.Count == 0)
                throw new ArgumentException("Results list cannot be null or empty.", nameof(results));

            if (string.IsNullOrWhiteSpace(outputPath))
                throw new ArgumentException("Output path cannot be null or empty.", nameof(outputPath));
        }
    }
}
